replicaCount: 1

image:
  repository: ghcr.io/hojatm-huma/sample-app
  pullPolicy: IfNotPresent
  tag: latest

livenessProbe: {}
readinessProbe: {}

s3:
  aws_region: eu-west-2
  bucket_name: helmatform-s3-v2
  iam_user_name: helmatform-s3-user-v2
